/**
 * vuex for arrangement
 * setters for arrangement
 */
const setters = {
  SET_ARRANGEMENT_ID: 'SET_ARRANGEMENT_ID',
  SET_ARRANGEMENT_MOVIE_ID: 'SET_ARRANGEMENT_MOVIE_ID',
  SET_ARRANGEMENT_HALL_ID: 'SET_ARRANGEMENT_HALL_ID',
  SET_ARRANGEMENT_START_TIME: 'SET_ARRANGEMENT_START_TIME',
  SET_ARRANGEMENT_STOP_TIME: 'SET_ARRANGEMENT_STOP_TIME',
  SET_ARRANGEMENT_SOLD_SEAT: 'SET_ARRANGEMENT_SOLD_SEAT',
  SET_ARRANGEMENT_PRICE: 'SET_ARRANGEMENT_PRICE',
  SET_ARRANGEMENT:'SET_ARRANGEMENT'
}
export default setters
