const setters = {
  SET_MOVIE_ID: 'SET_MOVIE_ID',
  SET_MOVIE_NAME: 'SET_MOVIE_NAME',
  SET_MOVIE_DIRECTOR: 'SET_MOVIE_DIRECTOR',
  SET_MOVIE_DURATION: 'SET_MOVIE_DURATION',
  SET_MOVIE_ACTOR: 'SET_MOVIE_ACTOR',
  SET_MOVIE_COUNTRY: 'SET_MOVIE_COUNTRY',
  SET_MOVIE_COMPANY: 'SET_MOVIE_COMPANY',
  SET_MOVIE: 'SET_MOVIE'
}
export default setters
