/**
 * vuex for user
 * setters for state
 */
const setters = {
  SET_USER_INFO_NICKNAME: 'SET_USER_INFO_NICKNAME',
  SET_USER_INFO_AVATAR: 'SET_USER_INFO_AVATAR',
  SET_USER_INFO_GENDER: 'SET_USER_INFO_GENDER',
  SET_USER_INFO_BIRTHDAY: 'SET_USER_INFO_BIRTHDAY',
  SET_USER_INFO_PHONE: 'SET_USER_INFO_PHONE',
  SET_USER_INFO_PASSWORD: 'SET_USER_INFO_PASSWORD',
  SET_USER_INFO_ID: 'SET_USER_INFO_ID',
  SET_USER_INFO_ROLE: 'SET_USER_INFO_ROLE',
  SET_USER: 'SET_USER'
}
export default setters
